
name: Sync Fork with Upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@main

    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@main
      with:
        target_sync_branch: main
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: main
        upstream_sync_repo: cmliu/edgetunnel

    - name: New commits found
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "::notice file=README.md::🎈New commits were found to sync."
    
    - name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "::notice file=README.md::📭There were no new commits."
      
